// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smsservice.proto

/*
Package smsservice is a generated protocol buffer package.

It is generated from these files:
	smsservice.proto

It has these top-level messages:
	SMS
	Empty
*/
package smsservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SMS struct {
	Receiver string `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Text     string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Noop     bool   `protobuf:"varint,3,opt,name=noop" json:"noop,omitempty"`
}

func (m *SMS) Reset()                    { *m = SMS{} }
func (m *SMS) String() string            { return proto.CompactTextString(m) }
func (*SMS) ProtoMessage()               {}
func (*SMS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SMS) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *SMS) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SMS) GetNoop() bool {
	if m != nil {
		return m.Noop
	}
	return false
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SMS)(nil), "SMS")
	proto.RegisterType((*Empty)(nil), "Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SMSService service

type SMSServiceClient interface {
	Send(ctx context.Context, in *SMS, opts ...grpc.CallOption) (*Empty, error)
}

type sMSServiceClient struct {
	cc *grpc.ClientConn
}

func NewSMSServiceClient(cc *grpc.ClientConn) SMSServiceClient {
	return &sMSServiceClient{cc}
}

func (c *sMSServiceClient) Send(ctx context.Context, in *SMS, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/SMSService/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SMSService service

type SMSServiceServer interface {
	Send(context.Context, *SMS) (*Empty, error)
}

func RegisterSMSServiceServer(s *grpc.Server, srv SMSServiceServer) {
	s.RegisterService(&_SMSService_serviceDesc, srv)
}

func _SMSService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SMSService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceServer).Send(ctx, req.(*SMS))
	}
	return interceptor(ctx, in, info, handler)
}

var _SMSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SMSService",
	HandlerType: (*SMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SMSService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smsservice.proto",
}

func init() { proto.RegisterFile("smsservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0xce, 0x2d, 0x2e,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe4, 0x62,
	0x0e, 0xf6, 0x0d, 0x16, 0x92, 0xe2, 0xe2, 0x28, 0x4a, 0x4d, 0x4e, 0xcd, 0x2c, 0x4b, 0x2d, 0x92,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a,
	0x24, 0x98, 0xc0, 0xe2, 0x60, 0x36, 0x48, 0x2c, 0x2f, 0x3f, 0xbf, 0x40, 0x82, 0x59, 0x81, 0x51,
	0x83, 0x23, 0x08, 0xcc, 0x56, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x34, 0x52, 0xe2,
	0xe2, 0x0a, 0xf6, 0x0d, 0x0e, 0x86, 0xd8, 0x23, 0x24, 0xc2, 0xc5, 0x12, 0x9c, 0x9a, 0x97, 0x22,
	0xc4, 0xa2, 0x17, 0xec, 0x1b, 0x2c, 0xc5, 0xa6, 0x07, 0x56, 0x93, 0xc4, 0x06, 0xb6, 0xde, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xcf, 0x04, 0x81, 0x92, 0x00, 0x00, 0x00,
}
